[package]
name = "fluent_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "fluent_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
fluent = "0.8.0"
unic-langid = "0.6.1"
